### ISSUE TITLE
Auth Proxy in Docker showing wrong version

### ISSUE THREAD

**Issue by AASluke** [Ipmake/KOCity-Proxy#4]
Altough the latest version is 2.0.0 at the moment - when I run docker run ghcr.io/kocxyz/authproxy:v2.0.0 in the logs it shows version 1.1.0.

As far as I analyzed it, this is because the ghcr package has the tag 2.0.0 but actually contains 1.1.0 (as far as I can tell from the package.json inside the container.

**Comment by Ipmake** [comment]
Resolved with 612508b
